---
- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: get docker host ip
      become: yes
      shell: /sbin/ip route | awk '/default/ { print $3 }'
      register: dockerhost_ip
      
    - name: get docker host ip
      debug:
        msg:
          - "{{ dockerhost_ip.stdout }}"

  roles:
    - {
      role: ansible-role-aem-license,
      aem_license_key: "{{ aem_license_key }}",
      aem_license_name: "{{ aem_license_name }}",
      aem_port: "5502",
      aem_host: "{{ dockerhost_ip.stdout }}",
      debug_hide: false
    }
