---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - {
      role: aem_design.aem_license,
      aem_license_key: "your key",
      aem_license_name: "your company",
      aem_port: "4502",
      aem_host: "localhost",
      debug_hide: false,
      wait_timeout: 5
    }
